WIP

diff --git a/scripts/start-services b/scripts/start-services
--- a/scripts/start-services
+++ b/scripts/start-services
@@ -7,3 +7,23 @@ fi
 
 service elasticsearch start
 /bin/bash -c "/usr/bin/mysqld_safe &"
+
+# Now wait until mysql is online
+
+retries=10
+count=0
+
+while [ $count -lt $retries ]; do
+  mysql -uroot -e "SELECT 1" > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    echo "MySQL is available."
+    break
+  fi
+  count=$((count+1))
+  echo "MySQL is not available. Retrying..."
+  sleep 1
+done
+
+if [ $count -eq $retries ]; then
+  echo "Could not connect to MySQL after $retries retries."
+fi
